hz: 10
goal_tolerance: 2.0

roomba_radius: 0.17
max_speed: 0.3
min_speed: 0.0
max_yawrate: 2.0
max_accel: 4
max_dyawrate: 8.0

speed_reso: 0.05
yawrate_reso: 0.1
dt: 0.1
predict_time: 2.0

heading_score_gain: 0.05
velocity_score_gain: 1.0
dist_score_gain: 0.3
