hz: 10

roomba_radius: 0.25
max_speed: 1.0
min_speed: -0.1
max_yawrate: 5.0
max_accel: 1.0
max_dyawrate: 5.0

speed_reso: 0.1
yawrate_reso: 0.1
dt: 0.1
predict_time: 2.0

heading_score_gain: 0.4
velocity_score_gain: 0.3
dist_score_gain: 0.3
